# Generated by Django 3.2 on 2022-05-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_coocking_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='count',
            new_name='amount',
        ),
    ]
