# Generated by Django 3.2 on 2022-05-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_count_ingredientamount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurment_unit',
            new_name='measurement_unit',
        ),
    ]
